# m:\Projects\Experiment Orchestrator\app_config.yaml
# Configuration for the "Experiment Orchestrator" application

# Logging settings for the orchestrator
logging:
  file_level: "DEBUG"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  console_level: "WARNING"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s %(levelname)s [%(process)d:%(module)s] %(funcName)s: %(message)s"
  rotation:
    max_bytes: 10*1024*1024 # 10 MB
    backup_count: 32

paths:
  modules_root: "modules"       # Directory for user-defined Python modules
  artifacts_root: "artifacts"   # Root directory for storing experiment artifacts
  runtime_root: "runtime"       # Root directory for storing runtime data
  log_dir: "log"                # Directory for log files (as used by logger.py)

